export const FRIEND_REQUEST = 'friend_request'
export const FRIEND_GET_REQUEST ='friend_get_request'
export const FRIEND_REQUEST_DELETE = 'friend_request_delete'
export const FRIEND_GET_LIST = 'friend_get_list'
export const FRIEND_REQUEST_RECEIVED ='friend_request_received'
export const FRIEND_REQUEST_HANDLE = 'friend_request_handle'
export const FRIEND_DELETE ='friend_delete'
